version: "1"
services:
  - type: web
    name: astram-frontend
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    autoDeployTrigger: commit

    envVars:
      - key: NODE_ENV
        value: production

      - key: NEXT_PUBLIC_API_BASE_URL
        value: ""

      - key: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
        sync: false

      - key: NEXT_PUBLIC_MAPPLS_REST_API_KEY
        value: ""
        sync: false
      - key: GOOGLE_MAPS_SERVER_API_KEY
        sync: false
      - key: NEXT_PUBLIC_MAPPLS_SDK_LAYER
        value: "raster"

  - type: web
    name: astram-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:app --bind 0.0.0.0:$PORT --workers 2
    autoDeployTrigger: commit

    envVars:
      - key: CORS_ORIGINS
        value: ""
        sync: false
      - key: MAPPLS_REST_API_KEY
        value: ""

      - key: MAPPLS_WEB_SDK_KEY
        sync: false

      - key: MAPPLS_CLIENT_ID
        sync: false

      - key: MAPPLS_CLIENT_SECRET
        sync: false

      - key: FLASK_APP
        value: backend

      - key: FLASK_ENV
        value: production

      - key: FLASK_HOST
        value: 0.0.0.0

      - key: FLASK_PORT
        value: ""
